const API='';
const CHAT_TIMEOUT_MS=120000;
const state={status:'IDLE',started:0,model:'AUTO ROUTER',latency:'—',events:[],messages:[],audioQueue:[],playing:false};
const app=document.querySelector('#app');
app.innerHTML=`<div class="m3-shell"><header class="topbar"><div class="brand"><div class="brand-mark">U3</div><div><div class="brand-title">ULTRON</div><div class="brand-sub">MARK 3 · PERSONAL OPERATING INTELLIGENCE</div></div></div><div class="status"><span class="dot"></span><span id="statusText">ONLINE // IDLE</span></div></header><main class="workspace"><div class="globe-wrap"><canvas id="globe" class="globe" width="680" height="680"></canvas><div class="glow"></div><div class="core"></div><div class="ring r1"></div><div class="ring r2"></div><div class="hud"><div class="tl"><span>COGNITIVE LINK</span><span id="hudState">STABLE</span></div><div class="tr"><span>MODEL</span><span id="hudModel">AUTO ROUTER</span></div><div class="bl"><span>LATENCY</span><span id="hudLatency">—</span></div><div class="br"><span>MEMORY</span><span id="hudMemory">—</span></div></div></div><aside class="activity"><div class="activity-title">LIVE ACTIVITY</div><div id="activityList"></div></aside><section class="chat"><div class="chat-head">ASSISTANT CONSOLE</div><div id="messages" class="messages"></div><div class="composer"><textarea id="input" placeholder="Talk to ULTRON…" aria-label="Message"></textarea><button id="send">SEND</button></div></section></main><footer class="bottom"><div class="telemetry"><div class="telemetry-item"><span class="telemetry-label">MODEL</span><span class="telemetry-value" id="model">AUTO ROUTER</span></div><div class="telemetry-item"><span class="telemetry-label">TASK</span><span class="telemetry-value" id="task">READY</span></div><div class="telemetry-item"><span class="telemetry-label">MEMORY</span><span class="telemetry-value" id="memory">0</span></div><div class="telemetry-item"><span class="telemetry-label">COMMITMENTS</span><span class="telemetry-value" id="commitments">0</span></div></div><div class="hint">MARK 3 · Observe → Understand → Act → Verify → Learn</div></footer></div>`;
const els={statusText:document.querySelector('#statusText'),hudState:document.querySelector('#hudState'),hudModel:document.querySelector('#hudModel'),hudLatency:document.querySelector('#hudLatency'),hudMemory:document.querySelector('#hudMemory'),model:document.querySelector('#model'),task:document.querySelector('#task'),memory:document.querySelector('#memory'),commitments:document.querySelector('#commitments'),activityList:document.querySelector('#activityList'),messages:document.querySelector('#messages'),input:document.querySelector('#input'),send:document.querySelector('#send')};
function renderEvents(){els.activityList.innerHTML=state.events.slice(-14).reverse().map(e=>`<div class="event"><div class="event-state">${escapeHtml(e.type.replaceAll('_',' '))}</div><div class="event-label">${escapeHtml(e.label||e.reason||e.message||e.error||e.kind||'')}</div>${e.provider?`<div class="event-tool">PROVIDER · ${escapeHtml(e.provider)}</div>`:''}${e.tool?`<div class="event-tool">${escapeHtml(e.tool)}</div>`:''}${e.model?`<div class="event-tool">MODEL · ${escapeHtml(e.model)}</div>`:''}</div>`).join('');}
function addMessage(role,text,meta=''){const node=document.createElement('div');node.className=`msg ${role}`;node.textContent=text;els.messages.appendChild(node);if(meta){const m=document.createElement('div');m.className='msg meta';m.textContent=meta;els.messages.appendChild(m);}els.messages.scrollTop=els.messages.scrollHeight;}
function setState(s){state.status=s;els.statusText.textContent=`ONLINE // ${String(s).toUpperCase()}`;els.hudState.textContent=String(s).toUpperCase();}
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
async function refreshState(){try{const r=await fetch(`${API}/api/state`);const d=await r.json();els.memory.textContent=d.memory?.total??0;els.commitments.textContent=d.commitments?.length??0;els.hudMemory.textContent=String(d.memory?.total??0);}catch{}}
async function refreshModels(){try{const r=await fetch(`${API}/api/models`);const d=await r.json();const count=Number(d.live?.count||0);if(state.status==='IDLE'||state.status==='COMPLETE'){els.model.textContent=state.model&&state.model!=='—'?state.model:'AUTO ROUTER';els.hudModel.textContent=count?`${count} ROUTES READY`:'AUTO ROUTER';}}catch{if(state.status==='IDLE')els.hudModel.textContent='ROUTER OFFLINE';}}
function playVoice(event){if(!event?.audioUrl)return;state.audioQueue.push(event.audioUrl);drainVoice();}
async function drainVoice(){if(state.playing||!state.audioQueue.length)return;state.playing=true;setState('SPEAKING');const url=state.audioQueue.shift();const audio=new Audio(url);audio.volume=.92;audio.onended=()=>{state.playing=false;if(state.audioQueue.length)drainVoice();else setState('COMPLETE');};audio.onerror=()=>{state.playing=false;if(state.audioQueue.length)drainVoice();else setState('ERROR');};try{await audio.play();}catch{audio.onerror?.();}}
function connectEvents(){const es=new EventSource(`${API}/api/events`);const types=['task_started','context_ready','plan_created','model_selection','model_started','model_candidate_started','model_candidate_failed','model_candidate_succeeded','model_failed','tool_started','tool_completed','verification_complete','response_ready','task_completed','proactive_alert','model_catalog_unavailable','voice_started','voice_ready','voice_prefetch_next','voice_completed','voice_error'];types.forEach(type=>es.addEventListener(type,e=>{try{const ev=JSON.parse(e.data);state.events.push(ev);if(state.events.length>120)state.events.shift();if(type==='model_candidate_started'){state.model=ev.model||state.model;els.model.textContent=state.model;els.hudModel.textContent=state.model;setState('ROUTING');}else if(type==='model_candidate_failed'){setState('ROUTING');}else if(type==='model_candidate_succeeded'){state.model=ev.model||state.model;els.model.textContent=state.model;els.hudModel.textContent=state.model;setState('GENERATING');}else if(ev.model&&type!=='model_selection'&&type!=='model_started'){state.model=ev.model;els.model.textContent=ev.model;els.hudModel.textContent=ev.model;}if(ev.durationMs)els.hudLatency.textContent=`${Math.round(ev.durationMs)}ms`;if(type==='voice_ready')playVoice(ev);else if(type==='voice_started')setState('SPEAKING');else if(type==='task_completed'&&!state.playing)setState('COMPLETE');else if(type==='model_failed')setState('ERROR');else if(!['model_candidate_started','model_candidate_failed','model_candidate_succeeded'].includes(type))setState((ev.state||type).toUpperCase());renderEvents();}catch{}}));}
async function send(){const text=els.input.value.trim();if(!text)return;els.input.value='';addMessage('user',text);setState('THINKING');els.task.textContent='ACTIVE';const started=performance.now();els.send.disabled=true;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),CHAT_TIMEOUT_MS);try{const history=state.messages.slice(-10);const r=await fetch(`${API}/api/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history}),signal:controller.signal});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'ULTRON request failed.');const out=String(d.response||d.text||'').trim();if(!out)throw new Error('ULTRON returned an empty response.');state.model=d.model||state.model;els.model.textContent=state.model;els.hudModel.textContent=state.model;const elapsed=Math.round(performance.now()-started);els.hudLatency.textContent=`${elapsed}ms`;addMessage('assistant',out,`${state.model} · ${elapsed}ms`);state.messages.push({role:'user',content:text},{role:'assistant',content:out});}catch(err){const message=err?.name==='AbortError'?`ULTRON routing exceeded ${Math.round(CHAT_TIMEOUT_MS/1000)} seconds and was cancelled.`:err.message;addMessage('assistant',`I couldn't complete that request: ${message}`,'ERROR');setState('ERROR');}finally{clearTimeout(timeout);els.send.disabled=false;els.task.textContent='READY';await refreshState();}}
els.send.addEventListener('click',send);els.input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});
const canvas=document.querySelector('#globe'),ctx=canvas.getContext('2d');let rot=0,last=performance.now();const points=Array.from({length:150},(_,i)=>{const a=i*Math.PI*(3-Math.sqrt(5)),y=1-(i/149)*2,r=Math.sqrt(Math.max(0,1-y*y));return{x:r*Math.cos(a),y,z:r*Math.sin(a)};});const satellites=Array.from({length:5},(_,i)=>({a:i*1.2,s:.002+i*.0007,r:1.18+i*.07}));
function resize(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.25);canvas.width=Math.floor(rect.width*dpr);canvas.height=Math.floor(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);}new ResizeObserver(resize).observe(canvas);resize();
function draw(now){const dt=Math.min(32,now-last);last=now;const w=canvas.clientWidth,h=canvas.clientHeight,cx=w/2,cy=h/2,r=Math.min(w,h)*.35;ctx.clearRect(0,0,w,h);rot+=dt*.00045;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle='rgba(99,214,255,.12)';ctx.lineWidth=1;ctx.stroke();const projected=points.map(p=>{const x=p.x*Math.cos(rot)-p.z*Math.sin(rot),z=p.x*Math.sin(rot)+p.z*Math.cos(rot),scale=1/(1+z*.35);return{x:cx+x*r*scale,y:cy+p.y*r*scale,z,scale};});projected.sort((a,b)=>a.z-b.z);for(let i=0;i<projected.length;i++){const a=projected[i];if(a.z<-.55)continue;for(let j=i+1;j<projected.length;j++){const b=projected[j];if(b.z<-.3)continue;const d=Math.hypot(a.x-b.x,a.y-b.y);if(d<42){ctx.strokeStyle=`rgba(99,214,255,${Math.max(0,.10*(1-d/42))*a.scale})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}}}for(const p of projected){const alpha=.16+Math.max(0,p.z)*.55;ctx.fillStyle=`rgba(210,244,255,${alpha})`;ctx.beginPath();ctx.arc(p.x,p.y,1.1+p.scale*.7,0,Math.PI*2);ctx.fill();}satellites.forEach(s=>{s.a+=s.s*dt;const x=Math.cos(s.a)*r*s.r,y=Math.sin(s.a)*r*s.r*.48;ctx.fillStyle='rgba(99,214,255,.85)';ctx.beginPath();ctx.arc(cx+x,cy+y,2,0,Math.PI*2);ctx.fill();});requestAnimationFrame(draw);}requestAnimationFrame(draw);
connectEvents();refreshState();refreshModels();setInterval(refreshState,10000);setInterval(refreshModels,30000);setState('IDLE');addMessage('assistant','ULTRON Mark 3 online. I am ready to work with you, not merely answer you.','SYSTEM · READY');
