import {addObservation,listObservations,upsertPattern,getPattern,listPatterns,deletePattern,saveMemory,listMemory,savePurposeNode,savePurposeEdge,listPurpose} from "./db.mjs";
import {hashedVector,cosine,workflowSimilarity} from "./local-reflex-engine.mjs";

const SECRET_KEY=/(?:api[_-]?key|access[_-]?token|refresh[_-]?token|client[_-]?secret|password|cookie|authorization|credential|session[_-]?secret)/i;
const SECRET_VALUE=/(?:AIza[\w-]{20,}|sk-[A-Za-z0-9_-]{16,}|Bearer\s+[A-Za-z0-9._-]{12,}|(?:token|secret|password)\s*[:=]\s*\S{8,})/i;
const evidenceWeight={EXPLICIT_FACT:.9,EXPLICIT_PREFERENCE:1,OBSERVED_PATTERN:.28,TENTATIVE_INFERENCE:.15,HISTORICAL_PATTERN:.2,CORRECTION:-1};
export function sanitizeSemantic(value,depth=0){if(depth>6)return"[bounded]";if(Array.isArray(value))return value.slice(0,50).map(x=>sanitizeSemantic(x,depth+1));if(value&&typeof value==="object"){const out={};for(const[key,item]of Object.entries(value).slice(0,80))out[key]=SECRET_KEY.test(key)?"[redacted]":sanitizeSemantic(item,depth+1);return out;}if(typeof value==="string"){if(SECRET_VALUE.test(value))return"[redacted]";return value.slice(0,2000);}return value;}
function classWeight(evidenceClass,weight){const base=evidenceWeight[evidenceClass]??.15;return Math.max(-1,Math.min(1,Number(weight??base)));}
export function observe(input={}){const evidenceClass=String(input.evidenceClass||"OBSERVED_PATTERN"),safe=sanitizeSemantic(input.value??{}),observation=addObservation({...input,evidenceClass,value:safe,weight:classWeight(evidenceClass,input.weight)});return consolidate({scope:observation.scope,projectId:observation.projectId,kind:observation.kind,subject:observation.subject,evidenceId:observation.id});}
export function consolidate({scope="GLOBAL",projectId=null,kind="preference",subject,evidenceId=null}={}){const rows=listObservations({scope,projectId,kind,subject,limit:200}),positive=rows.filter(x=>x.weight>0),negative=rows.filter(x=>x.weight<0),explicit=positive.some(x=>["EXPLICIT_FACT","EXPLICIT_PREFERENCE"].includes(x.evidenceClass)),score=positive.reduce((n,x)=>n+x.weight,0)+negative.reduce((n,x)=>n+x.weight,0),count=rows.length;let confidence=explicit?Math.max(.88,Math.min(.99,.84+positive.length*.03)):Math.max(.05,Math.min(.9,.12+Math.max(0,score)*.22+Math.max(0,positive.length-1)*.08));const status=explicit?"confirmed":positive.length>=5&&confidence>=.72?"consolidated":positive.length>=3?"candidate":positive.length>=2?"tentative":"observed";if(negative.length>positive.length)confidence=Math.min(confidence,.3);const latest=rows[0],pattern=upsertPattern({type:kind==="workflow"?"workflow":kind,scope,projectId,subject,description:String(latest?.value?.description||latest?.value?.summary||subject),value:latest?.value||{},confidence,evidenceCount:count,positiveEvidence:positive.length,negativeEvidence:negative.length,status:negative.length>positive.length?"superseded":status,lastObservedAt:latest?.createdAt,lastConfirmedAt:explicit?latest?.createdAt:null,evidenceId,action:"consolidated"});return{observation:latest,pattern};}
export function recordCorrection({patternId,scope="GLOBAL",projectId=null,kind="preference",subject,correctedValue,missionId=null}={}){const current=patternId?getPattern(patternId):listPatterns({scope,projectId,type:kind,limit:100}).find(x=>x.subject===subject);if(current)upsertPattern({...current,confidence:Math.max(.05,current.confidence-.55),negativeEvidence:current.negativeEvidence+1,status:"superseded",action:"corrected"});const correctedSubject=subject||current?.subject;if(!correctedSubject)throw new Error("CORRECTION_SUBJECT_REQUIRED");return observe({evidenceClass:"EXPLICIT_PREFERENCE",scope,projectId,kind,subject:correctedSubject,value:{value:sanitizeSemantic(correctedValue),supersedes:current?.id||null},missionId});}
export function decayPatterns({now=Date.now(),projectId=null}={}){const rows=listPatterns({projectId,limit:500}),updated=[];for(const row of rows){if(row.status==="confirmed"||row.status==="disabled")continue;const ageDays=Math.max(0,(now-Date.parse(row.lastObservedAt||row.updatedAt))/(864e5));if(ageDays<30)continue;const factor=Math.pow(.96,Math.floor(ageDays/30)),next=Math.max(.05,Number((row.confidence*factor).toFixed(4)));if(next<row.confidence-.001)updated.push(upsertPattern({...row,confidence:next,status:next<.25?"stale":row.status,action:"decayed"}));}return updated;}
export function setPatternState(id,action,value=null){const row=getPattern(id);if(!row)throw new Error("PATTERN_NOT_FOUND");if(action==="forget"){deletePattern(id);return{ok:true,id,forgotten:true};}if(action==="confirm")return upsertPattern({...row,confidence:Math.max(.95,row.confidence),status:"confirmed",lastConfirmedAt:new Date().toISOString(),action:"confirmed"});if(action==="disable")return upsertPattern({...row,status:"disabled",action:"disabled"});if(action==="correct")return recordCorrection({patternId:id,scope:row.scope,projectId:row.projectId,kind:row.type,subject:row.subject,correctedValue:value});throw new Error("PATTERN_ACTION_NOT_SUPPORTED");}
export function remember(input={}){const safeSummary=String(sanitizeSemantic(input.summary||"")).trim();if(!safeSummary)throw new Error("MEMORY_SUMMARY_REQUIRED");return saveMemory({...input,summary:safeSummary,payload:sanitizeSemantic(input.payload||{})});}
export function searchMemory(query,{projectId=null,limit=5}={}){const q=hashedVector(query);return listMemory({projectId,limit:200}).map(item=>({...item,similarity:Number(cosine(q,hashedVector(`${item.summary} ${JSON.stringify(item.payload)}`)).toFixed(4))})).filter(x=>x.similarity>=.12).sort((a,b)=>b.similarity-a.similarity||b.confidence-a.confidence).slice(0,Math.max(1,Math.min(10,limit)));}
export function recordWorkflow({name,skillIds,scope="GLOBAL",projectId=null,missionId=null,explicit=false}={}){return observe({evidenceClass:explicit?"EXPLICIT_PREFERENCE":"OBSERVED_PATTERN",scope,projectId,kind:"workflow",subject:String(name),value:{description:String(name),skillIds:[...new Set(skillIds||[])].slice(0,12)},missionId});}
export function relevantPatterns(query,{projectId=null,limit=5}={}){const rows=[...listPatterns({scope:"GLOBAL",projectId:null,limit:100}),...(projectId?listPatterns({scope:"PROJECT",projectId,limit:100}):[])].filter(x=>!["disabled","superseded","stale"].includes(x.status));return workflowSimilarity(query,rows).slice(0,limit);}
export function linkPurpose({source,target,relation="supports",scope="GLOBAL",projectId=null,confidence=.6,evidence={}}={}){const sourceNode=savePurposeNode({...(typeof source==="string"?{label:source,type:"task"}:source),scope,projectId,confidence}),targetNode=savePurposeNode({...(typeof target==="string"?{label:target,type:"goal"}:target),scope,projectId,confidence});const edge=savePurposeEdge({sourceId:sourceNode.id,relation,targetId:targetNode.id,confidence,evidence:sanitizeSemantic(evidence)});return{source:sourceNode,target:targetNode,edge};}
export function intelligenceSnapshot({projectId=null}={}){decayPatterns({projectId});const patterns=[...listPatterns({scope:"GLOBAL",projectId:null,limit:30}),...(projectId?listPatterns({scope:"PROJECT",projectId,limit:30}):[])].filter(x=>x.status!=="disabled");return{patterns,purpose:listPurpose({projectId,limit:50}),memory:listMemory({projectId,limit:30}),policy:{singleObservationMaximumConfidence:.45,explicitEvidenceDominates:true,projectIsolation:true,secretPersistence:false,rawLogPersistence:false}};}
