import crypto from "node:crypto";
import {compileCommand,parseSheetTarget} from "./command-control-plane.mjs";
import {listSkillContracts,getSkillContract,publicSkillContract,PARAMETER_OWNERSHIP} from "./skill-contracts.mjs";
import {retrieveSkills,matchSchemas} from "./local-reflex-engine.mjs";
import {relevantPatterns} from "./intelligence-engine.mjs";
import {saveSkillInvocation} from "./db.mjs";

const priority={system_lock:1,explicit_user:2,active_mission:3,confirmed_context:4,user_preference:5,skill_default:6,deterministic:7,local_reflex:8,api_model:9,user_confirmation:2};
const now=()=>new Date().toISOString();
const evidence=(value,source,confidence=1,ownership=null)=>({value,source,confidence,timestamp:now(),ownership});
function valueOf(parameters,key){const item=parameters?.[key];return item&&typeof item==="object"&&"value" in item?item.value:item;}
function nonempty(value){return value!==undefined&&value!==null&&value!==""&&(!Array.isArray(value)||value.length>0);}
function deepFreeze(value){if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const item of Object.values(value))deepFreeze(item);}return value;}
function inferSkillId(intent,text){const n=String(text).toLowerCase();if(/^\s*leads?\s*$/.test(n))return"apollo.company.discovery";if(/\bapollo\b/.test(n)&&/\b(find|discover|source)\b/.test(n)&&/\b(companies|company|organizations)\b/.test(n))return"apollo.company.discovery";if(/\b(?:start|another)\b/.test(n)&&/\bsaas\b/.test(n)&&/\b(?:outreach|lead)\b/.test(n))return"apollo.company.discovery";if(intent.domain==="mission-control")return intent.operation==="resume"?"mission.resume":"mission.inspect";const map={"apollo-company-discovery":"apollo.company.discovery","apollo-contact-enrichment":"apollo.contact.enrichment","linkedin-company-research":"linkedin.company.discovery","creator-research":"creator.research","reel-production":"reel.plan","coding":"github.code.change"};if(map[intent.domain])return map[intent.domain];if(/\bemail\b/.test(n))return/\b(send|deliver)\b/.test(n)?"email.send":"email.draft";if(/\b(research|look up|find out)\b/.test(n))return"web.research";return null;}
function explicitParameters(text,intent,context={}){const sheet=parseSheetTarget(text,context),out={};for(const[key,value]of Object.entries({targetCount:/\b(?:find|get|bring|discover|add|fill|research|target(?:\s+of)?)[^\d]{0,12}\d{1,4}\b|\b\d{1,4}\s+(?:unique\s+)?(?:companies|businesses|organizations|leads|creators)\b/i.test(String(text))?intent.targetCount:null,country:intent.country,companyConcepts:intent.companyConcepts,employeeMin:intent.employeeMin,employeeMax:intent.employeeMax,spreadsheetId:sheet.spreadsheetId,sheetId:sheet.sheetId,worksheet:sheet.worksheet,missionId:intent.missionId,repository:context.repository,branch:context.branch})){if(nonempty(value))out[key]=value;}const n=String(text);if(!out.companyConcepts&&/\bsaas\b/i.test(n))out.companyConcepts=["saas","software as a service"];const quoted=[...n.matchAll(/["“]([^"”]{2,100})["”]/g)].map(x=>x[1].trim());if(/\b(?:creators?|influencers?)\b/i.test(n)){const niche=n.match(/(?:creator|influencer)s?\s+(?:in|for|about)\s+([a-z][a-z &-]{2,50})/i)?.[1]||n.match(/(?:research\s+)?(?:\d+\s+)?([a-z][a-z &-]{2,40})\s+(?:creators?|influencers?)/i)?.[1];if(niche)out.niche=niche.trim();}if(/\b(?:job|role|hiring)\b/i.test(n)){const role=n.match(/(?:for|hiring)\s+([A-Za-z][A-Za-z0-9 +#.-]{1,50}?)(?:\s+(?:role|job|in|at|within|posted|remote)|[,.;]|$)/i)?.[1];if(role)out.role=role.trim();}if(/\bremote\b/i.test(n))out.remoteOnly=true;const days=n.match(/(?:past|last|within)\s+(\d+)\s+days?/i)?.[1];if(days)out.postedWithinDays=Number(days);if(/\bemail\b/i.test(n)){const recipient=n.match(/(?:send|email|mail)\s+([A-Z][a-z]+|[^\s,]+@[^\s,]+)/)?.[1]||n.match(/send\s+([A-Z][a-z]+)\s+an?\s+email/i)?.[1];if(recipient)out.recipient=recipient;const purpose=n.match(/(?:about|regarding)\s+(.+)$/i)?.[1];if(purpose)out.purpose=purpose.trim();}if(/\b(reel|short video)\b/i.test(n))out.topic=quoted[0]||n.match(/(?:about|for)\s+(.+)$/i)?.[1]?.trim();if(/\b(code|github|repository|bug|implement|refactor)\b/i.test(n))out.objective=n.trim();if(/\b(research|extract)\b/i.test(n)&&!out.topic)out.topic=n.replace(/^(?:please\s+)?(?:research|find out|look up)\s*/i,"").trim();return out;}
function assign(target,key,value,source,definition,confidence=1){if(!nonempty(value))return;const existing=target[key];if(existing&&priority[existing.source]<=priority[source])return;if(definition?.ownership===PARAMETER_OWNERSHIP.SYSTEM_LOCKED&&source!=="system_lock")return;target[key]=evidence(value,source,confidence,definition?.ownership||null);}
function validateValue(key,item,definition){const value=item?.value;if(!nonempty(value))return definition.required?`${key} is required`:null;if(definition.type==="integer"&&(!Number.isInteger(Number(value))||Number(value)<Number(definition.min??-Infinity)||Number(value)>Number(definition.max??Infinity)))return`${key} must be an integer${definition.min!=null?` from ${definition.min}`:""}${definition.max!=null?` to ${definition.max}`:""}`;if(definition.type==="array"&&!Array.isArray(value))return`${key} must be a list`;if(definition.type==="boolean"&&typeof value!=="boolean")return`${key} must be true or false`;return null;}
function questionFor(keys,contract){const labels=keys.map(key=>key.replace(/([A-Z])/g," $1").toLowerCase());if(keys.length===1)return`What ${labels[0]} should I use for ${contract.name}?`;return`I can continue the same mission after you provide: ${labels.join(", ")}.`;}
function planFor(primary,text){const n=String(text).toLowerCase(),ids=[];if(primary.id==="apollo.company.discovery"){ids.push(primary.id);if(/\b(sheet|spreadsheet|worksheet|write|fill|add)\b/.test(n))ids.push("google.sheet.append");if(/\b(enrich|poc|contact|email|phone)\b/.test(n)){ids.push("apollo.contact.enrichment");if(/\b(sheet|spreadsheet|worksheet|write|fill|add)\b/.test(n))ids.push("google.sheet.update");}}else if(primary.id==="reel.plan"&&/\b(create|make|produce|render)\b/.test(n))ids.push("reel.plan","reel.create","reel.render");else if(primary.id==="email.send")ids.push("email.draft","email.send");else ids.push(primary.id);const unique=ids.filter((x,i)=>ids.indexOf(x)===i);return unique.map((id,index)=>{const skill=getSkillContract(id),previous=index?getSkillContract(unique[index-1]):null,compatibility=previous?matchSchemas(previous.outputSchema,skill.inputSchema):{compatible:true,matched:[],missing:[],score:1};return{index,skillId:id,state:index===0?"ready":"pending",compatible:compatibility.compatible,compatibility};});}
export function resolveSkillRequest(text,context={}){const intent=compileCommand(text,context),patterns=relevantPatterns(text,{projectId:context.projectId||null,limit:5}),retrieval=retrieveSkills(text,listSkillContracts(),{patterns}),deterministicId=inferSkillId(intent,text),best=deterministicId?{skillId:deterministicId,score:Math.max(.9,intent.confidence||0),source:"deterministic"}:retrieval.candidates[0]||null;if(!best||best.score<.22)return{matched:false,intent,retrieval,patterns,escalationRequired:true};const contract=getSkillContract(best.skillId);if(!contract)return{matched:false,intent,retrieval,patterns,escalationRequired:true};const parameters={},explicit=explicitParameters(text,intent,context),active=context.activeInvocation?.parameters||{};for(const[key,definition]of Object.entries(contract.parameters)){if(definition.ownership===PARAMETER_OWNERSHIP.SYSTEM_LOCKED)assign(parameters,key,definition.default,"system_lock",definition,1);if(nonempty(explicit[key]))assign(parameters,key,explicit[key],"explicit_user",definition,1);if(nonempty(valueOf(active,key)))assign(parameters,key,valueOf(active,key),"active_mission",definition,Number(active[key]?.confidence||.95));if(nonempty(context.confirmed?.[key]))assign(parameters,key,context.confirmed[key],"confirmed_context",definition,.95);const preference=patterns.find(x=>x.subject===key&&x.status!=="superseded");if(preference&&nonempty(preference.value?.value))assign(parameters,key,preference.value.value,"user_preference",definition,preference.confidence);if(nonempty(definition.default))assign(parameters,key,definition.default,"skill_default",definition,1);if(nonempty(retrieval.candidates.find(x=>x.skillId===contract.id)?.arguments?.[key]))assign(parameters,key,retrieval.candidates.find(x=>x.skillId===contract.id).arguments[key],"local_reflex",definition,retrieval.confidence);}
 const errors=[],missing=[];for(const[key,definition]of Object.entries(contract.parameters)){const problem=validateValue(key,parameters[key],definition);if(problem){errors.push(problem);if(definition.required&&!nonempty(valueOf(parameters,key)))missing.push(key);}}const invocation={skillId:contract.id,invocationId:`invocation-${crypto.randomUUID()}`,missionId:context.missionId||null,parameters:Object.fromEntries(Object.entries(parameters).map(([k,v])=>[k,v.value])),parameterEvidence:parameters,context:{projectId:context.projectId||null,sessionId:context.sessionId||null,screen:context.screen?.active?"shared":"not_shared",pageUrl:context.page?.url||null},approvalState:{required:Boolean(contract.approval?.required),scope:contract.approval?.scope||"none",status:contract.approval?.required?"required":"not_required"},authState:{requirements:contract.authentication,status:"unchecked"},executionState:missing.length?"waiting_input":"compiled",missingParameters:missing,validationErrors:errors,plan:planFor(contract,text),selection:{source:best.source,confidence:Number(best.score),candidates:retrieval.candidates.slice(0,5)},createdAt:now()};return{matched:true,contract,invocation:deepFreeze(invocation),publicContract:publicSkillContract(contract),question:missing.length?questionFor(missing,contract):null,retrieval,patterns,escalationRequired:!deterministicId&&retrieval.escalationRequired};}
export function persistInvocation(invocation){return saveSkillInvocation(invocation);}
export function continueInvocation(invocation,answer,context={}){const contract=getSkillContract(invocation.skillId);if(!contract)throw new Error("SKILL_CONTRACT_NOT_FOUND");const missing=[...(invocation.missingParameters||[])],values={...invocation.parameters},proof={...invocation.parameterEvidence},text=String(answer||"").trim();if(!text)throw new Error("PARAMETER_VALUE_REQUIRED");if(missing.length>1){const number=Number(text.match(/\b(\d{1,4})\b/)?.[1]);const country=text.match(/\b(India|United States|USA|UK|Germany|Singapore|Australia|Canada)\b/i)?.[1];for(const key of missing){if(key.toLowerCase().endsWith("count")&&number)values[key]=number;else if(/country/i.test(key)&&country)values[key]=[country];}}if(missing.length===1&&!nonempty(values[missing[0]])){const key=missing[0],definition=contract.parameters[key];values[key]=definition.type==="integer"?Number(text):definition.type==="array"?text.split(/[,;]+/).map(x=>x.trim()).filter(Boolean):definition.type==="boolean"?/^(?:yes|true|1)$/i.test(text):text;}for(const key of missing)if(nonempty(values[key]))proof[key]=evidence(values[key],"user_confirmation",1,contract.parameters[key]?.ownership);const remaining=missing.filter(key=>!nonempty(values[key])),errors=[];for(const[key,definition]of Object.entries(contract.parameters)){const problem=validateValue(key,proof[key]||{value:values[key]},definition);if(problem&&!remaining.includes(key))errors.push(problem);}const next={...invocation,parameters:values,parameterEvidence:proof,context:{...invocation.context,...context},missingParameters:remaining,validationErrors:errors,executionState:remaining.length||errors.length?"waiting_input":"compiled",updatedAt:now()};return{invocation:deepFreeze(next),question:remaining.length?questionFor(remaining,contract):errors[0]||null,contract};}
export function safeModelPayload(invocation){return{skillId:invocation.skillId,invocationId:invocation.invocationId,missionId:invocation.missionId,parameters:invocation.parameters,parameterEvidence:Object.fromEntries(Object.entries(invocation.parameterEvidence||{}).map(([key,item])=>[key,{source:item.source,confidence:item.confidence,ownership:item.ownership}])),context:invocation.context,plan:invocation.plan.map(x=>({skillId:x.skillId,index:x.index,state:x.state,compatible:x.compatible}))};}
