import {useEffect,useMemo,useRef,useState} from "react";
import {Icon} from "./Icon";
import {Dialog} from "./Dialog";
export interface PaletteAction{id:string;title:string;detail:string;group:string;shortcut?:string;}
export function CommandPalette(p:{open:boolean;actions:PaletteAction[];onClose:()=>void;onChoose:(id:string)=>void}){
 const[query,setQuery]=useState(""),[index,setIndex]=useState(0),[recent,setRecent]=useState<string[]>(()=>{try{const v=JSON.parse(localStorage.getItem("ultron.recentCommands")||"[]");return Array.isArray(v)?v.slice(0,4):[]}catch{return[]}}),list=useRef<HTMLDivElement>(null);
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();return p.actions.filter(a=>!q||(a.title+" "+a.detail).toLowerCase().includes(q)).map(a=>({...a,group:!q&&recent.includes(a.id)?"Recent":a.id.startsWith("new-")?"Create":/status|system/.test(a.id)?"Actions":"Navigate"})).sort((a,b)=>["Recent","Create","Navigate","Actions"].indexOf(a.group)-["Recent","Create","Navigate","Actions"].indexOf(b.group))},[p.actions,query,recent]);
 useEffect(()=>{if(p.open){setQuery("");setIndex(0)}},[p.open]);
 useEffect(()=>{list.current?.querySelector('[aria-selected="true"]')?.scrollIntoView({block:"nearest"})},[index]);
 function choose(id:string){const next=[id,...recent.filter(x=>x!==id)].slice(0,4);setRecent(next);try{localStorage.setItem("ultron.recentCommands",JSON.stringify(next))}catch{}p.onChoose(id)}
 if(!p.open)return null;
 return <Dialog title="Commands" onClose={p.onClose} className="command-palette"><label className="palette-search"><Icon name="search"/><input autoFocus role="combobox" aria-label="Search commands" aria-expanded="true" aria-controls="command-results" aria-activedescendant={rows[index]?"command-"+rows[index].id:undefined} value={query} onChange={e=>{setQuery(e.target.value);setIndex(0)}} placeholder="Type a command or search…" onKeyDown={e=>{if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();setIndex(i=>Math.max(0,Math.min(rows.length-1,i+(e.key==="ArrowDown"?1:-1))))}if(e.key==="Enter"&&rows[index])choose(rows[index].id)}}/><button aria-label="Close commands" onClick={p.onClose}><kbd>Esc</kbd></button></label><div ref={list} id="command-results" role="listbox" aria-label="Commands" className="palette-results">{rows.map((a,i)=><div key={a.id}>{(i===0||rows[i-1].group!==a.group)&&<h3 className="palette-group">{a.group}</h3>}<button id={"command-"+a.id} role="option" aria-selected={index===i} className={index===i?"selected":""} onMouseEnter={()=>setIndex(i)} onClick={()=>choose(a.id)}><span className="palette-symbol"><Icon name={a.group==="Create"?"plus":a.group==="Actions"?"check":"arrow"}/></span><span><b>{a.title}</b><small>{a.detail}</small></span>{a.shortcut&&<kbd>{a.shortcut}</kbd>}</button></div>)}{!rows.length&&<p className="empty-list">No matching command. Try “missions” or “Google”.</p>}</div><footer><span>↑ ↓ Navigate</span><span>↵ Open</span></footer></Dialog>;
}
