import type{LiveEvent,Mission,ModelRoute,SystemOverview,ViewMode}from"../types";
const title=(v:string)=>v.replace(/[-_]/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export function ControlView(p:{view:ViewMode;overview:SystemOverview|null;missions:Mission[];models:ModelRoute[];events:LiveEvent[];onMission:(id:string)=>void;onCommand:(text:string)=>void;onUpdateMission:(id:string,patch:Record<string,unknown>)=>Promise<void>}){
 const o=p.overview;if(p.view==="tasks")return <Shell eyebrow="EXECUTION QUEUE" title="Tasks & approvals" copy="Durable missions and current runtime work, ordered from live state."><div className="card-list">{p.missions.filter(m=>!["completed","cancelled"].includes(m.status)).map(m=><article className="data-card" key={m.id}><span className={"status-glyph "+m.status}/><button className="task-main" onClick={()=>p.onMission(m.id)}><b>{m.objective}</b><small>{m.nextAction||m.status}</small></button><div className="task-actions"><strong>{title(m.status)}</strong>{m.status==="paused"||m.status==="blocked"?<button onClick={()=>void p.onUpdateMission(m.id,{status:"active"})}>Resume</button>:<button onClick={()=>void p.onUpdateMission(m.id,{status:"paused"})}>Pause</button>}<button className="danger" onClick={()=>void p.onUpdateMission(m.id,{status:"cancelled",nextAction:null})}>Cancel</button></div></article>)}</div></Shell>;
 if(p.view==="skills")return <Shell eyebrow="CAPABILITY DIRECTORY" title="Skills" copy="Installed Hermes skills discovered from the active Mark 4 workspace."><div className="knowledge-grid">{(o?.skills||[]).map(s=><article className="knowledge-card" key={s.id}><header><span>{s.name.slice(0,1)}</span><i className={s.available?"ok":"warn"}/></header><h3>{s.name}</h3><p>{s.summary}</p><footer><code>{s.id}</code><button onClick={()=>p.onCommand(`Explain the ${s.name} skill, its inputs, outputs and approval requirements.`)}>Ask ULTRON</button></footer></article>)}</div></Shell>;
 if(p.view==="memory")return <Shell eyebrow="COGNITIVE CONTINUITY" title="Memory & patterns" copy="Only persisted Mark 4 memory is shown here."><section className="glass-panel reading-card"><span className="eyebrow">PERSISTED MEMORY</span><h2>{o?.memory.available?"Workspace memory loaded":"No memory source available"}</h2><p>{o?.memory.excerpt||"The runtime has not reported a persisted memory document."}</p>{o?.memory.updatedAt&&<small>Updated {new Date(o.memory.updatedAt).toLocaleString()}</small>}</section><section className="glass-panel reading-card"><span className="eyebrow">PATTERNS</span><h2>Observed runtime patterns</h2><div className="pattern-list">{patternRows(p.events).map(row=><div key={row.label}><b>{row.value}</b><span>{row.label}</span></div>)}</div></section></Shell>;
 if(p.view==="models")return <Shell eyebrow="INTELLIGENCE FABRIC" title="Model broker" copy="Configured routes, measured health and cooldown state from the gateway."><div className="knowledge-grid">{p.models.map(route=><article className="knowledge-card" key={route.id}><header><span>{route.role.slice(0,1).toUpperCase()}</span><i className={route.configured&&!route.cooling?"ok":"warn"}/></header><h3>{route.role}</h3><p>{[route.provider,route.model].filter(Boolean).join(" · ")||"Hermes automatic route"}</p><dl><div><dt>Score</dt><dd>{route.score??"—"}</dd></div><div><dt>Status</dt><dd>{route.cooling?"Cooling":route.configured?"Ready":"Unconfigured"}</dd></div><div><dt>Calls</dt><dd>{String((route.metrics as any)?.calls??"—")}</dd></div></dl></article>)}</div></Shell>;
 if(p.view==="artifacts")return <Shell eyebrow="VERIFIED OUTPUTS" title="Artifacts" copy="Mission outputs and destinations with their recorded provenance."><div className="card-list">{(o?.artifacts||[]).length?(o?.artifacts||[]).map((a:any,i)=><article className="artifact-card" key={`${a.missionId}-${i}`}><span>{title(String(a.type||"artifact"))}</span><div><b>{String(a.name||a.sheetName||a.range||"Mission artifact")}</b><small>{String(a.mission||a.missionId)}</small></div>{a.url?<a href={String(a.url)} target="_blank" rel="noreferrer">Open</a>:<strong>Stored</strong>}</article>):<div className="empty-state"><b>No recorded artifact</b><span>Completed mission outputs appear here.</span></div>}</div></Shell>;
 if(p.view==="system")return <Shell eyebrow="RUNTIME OBSERVABILITY" title="System health" copy="Services and repository status reported by the local gateway."><div className="metric-grid system-metrics">{(o?.services||[]).map(s=><article className="metric-card" key={s.id}><span>{s.label}</span><strong className={s.status}>{s.status}</strong><small>{s.detail}</small></article>)}</div><Workspace overview={o}/></Shell>;
 return <Shell eyebrow="SYSTEM DICTIONARY" title="About ULTRON" copy="Mark 4 product identity and inspectable architecture."><section className="glass-panel about-card"><div className="about-mark">U<span>4</span></div><div><span className="eyebrow">PURPOSE</span><h2>{o?.purpose.name||"ULTRON Mark 4"}</h2><p>{o?.purpose.statement||"Personal operating intelligence."}</p><small>Source · {o?.purpose.source||"Runtime"}</small></div></section><div className="dictionary-grid">{[["Mission","A durable objective with state, evidence, blockers and outputs."],["Skill","An installed capability contract exposed through Hermes."],["Model route","A measured provider/model assignment selected by the broker."],["Artifact","A recorded result linked to its producing mission."],["Branch","A conversation fork with its parent and anchor context."],["Approval","A scoped policy decision recorded against a run or mission."]].map(([k,v])=><article key={k}><b>{k}</b><p>{v}</p></article>)}</div></Shell>;
}
function Shell(p:{eyebrow:string;title:string;copy:string;children:any}){return <section className="control-view page-flow"><header className="page-header"><div><span className="eyebrow">{p.eyebrow}</span><h1>{p.title}</h1><p>{p.copy}</p></div></header>{p.children}</section>}
function Workspace({overview}:{overview:SystemOverview|null}){const w=overview?.workspace;return <section className="workspace-card glass-panel"><header><div><span className="eyebrow">GIT WORKSPACE</span><h2>{w?.repository||"Repository unavailable"}</h2></div><strong>{w?.branch||"—"}</strong></header><div className="workspace-summary"><div><span>HEAD</span><b>{w?.head||"—"}</b><small>{w?.subject||w?.error}</small></div><div><span>UPSTREAM</span><b>{w?.upstream||"Not configured"}</b><small>{w?.dirty?`${w.changes?.length||0} local changes`:"Working tree clean"}</small></div><div><span>WORKTREES</span><b>{w?.worktrees?.length||0}</b><small>Read-only repository view</small></div></div>{w?.changes?.length?<div className="change-list">{w.changes.slice(0,12).map((c,i)=><div key={c.path+i}><code>{c.code}</code><span>{c.path}</span></div>)}</div>:<div className="empty-state compact"><b>No local changes</b><span>Repository status is clean.</span></div>}</section>}
function patternRows(events:LiveEvent[]){const counts=new Map<string,number>();for(const e of events){const key=e.type.split(".")[0]||"runtime";counts.set(key,(counts.get(key)||0)+1)}return[...counts].sort((a,b)=>b[1]-a[1]).slice(0,6).map(([label,value])=>({label,value}))}
