import {useState} from "react";
import {api} from "../api";
import type {LiveEvent,Mission,ModelRoute,SystemOverview,ViewMode} from "../types";

const manual=[
 ["ULTRON","ULTRON turns a request into observable, recoverable work. Start in Chat, follow progress in Missions, and review deliverables in Outputs."],
 ["Local Reflex Engine","Intent parsing, hashed semantic matching, skill and schema selection, workflow similarity, and confidence scoring run in process. No model is loaded and no separate inference process is started."],
 ["What intelligence learns","Repeated successful workflows can become tentative scoped patterns. Explicit corrections and preferences carry more weight than observations. A single observation never becomes a trusted preference."],
 ["What intelligence never stores","Secrets and raw logs are excluded from structured memory. Project patterns stay in their project scope. You can confirm, disable, correct, or forget visible patterns from System."],
 ["Recovery","Missions retain their stage, parameters, evidence, and invocation identity. Missing input pauses the same invocation; resolving it continues from that checkpoint."],
 ["Skills","Each skill declares typed parameters, ownership, permissions, cost, authentication, side effects, executor, verifier, recovery policy, and compatible workflow inputs and outputs."],
 ["Approvals","Paid providers and external writes remain visible and scoped. Read the requested action before allowing it; approval never changes parameter ownership or verification rules."],
 ["Models","Direct model providers remain available for cognition. Deterministic work stays in the Local Reflex Engine. FreeLLMAPI is registered as a local ambiguity route and is not part of deterministic execution."],
 ["Memory","Structured semantic memory stores bounded summaries and provenance. It complements the existing Markdown continuity file; it does not replace mission evidence."],
 ["Conversation branches","Branch on an assistant message to explore a separate conversation. This is distinct from a Git branch."],
 ["Coding context","System reports the repository, branch, commit, and working state. Tests and verification remain part of coding mission completion."],
 ["Voice and screen","Chat accepts text, voice, files, and shared screen context. Supply an exact URL when the destination matters, especially for Google Sheets."],
];
const words=(value?:string[])=>value?.length?value.join(", "):"None";
const pct=(value:number)=>Math.round(Number(value||0)*100)+"%";

export function ControlView(p:{view:ViewMode;overview:SystemOverview|null;missions:Mission[];models:ModelRoute[];events:LiveEvent[];onMission:(id:string)=>void;onCommand:(text:string)=>void;onUpdateMission:(id:string,patch:Record<string,unknown>)=>Promise<void>;onRefresh?:()=>Promise<void>}){
 const[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[working,setWorking]=useState(""),[notice,setNotice]=useState(""),o=p.overview;
 async function pattern(id:string,action:string){setWorking(id+action);setNotice("");try{await api.patternAction(id,action);await p.onRefresh?.();setNotice(`Pattern ${action} complete.`)}catch(e:any){setNotice(e.message||"Pattern action failed.")}finally{setWorking("")}}
 if(p.view==="skills"){
  const skills=o?.skills||[],categories=["All",...new Set(skills.map(s=>s.category||"General"))],rows=skills.filter(s=>(category==="All"||(s.category||"General")===category)&&(s.name+" "+s.summary+" "+s.id).toLowerCase().includes(query.toLowerCase()));
  return <Shell title="Skills" copy="Inspect the exact contract ULTRON will compile before execution."><input className="product-search" aria-label="Search skills" placeholder="Search capabilities…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="filter-bar" role="group" aria-label="Skill categories">{categories.map(c=><button key={c} aria-pressed={c===category} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="knowledge-grid">{rows.map(s=><article className="knowledge-card" key={s.id}><header><span>{s.name.slice(0,1)}</span><b className="status-badge success">Ready</b></header><small>{s.category} · {s.id}</small><h3>{s.name}</h3><p className="clamp-copy">{s.summary}</p><div className="skill-facts"><span>{s.costClass||"free"} · {s.sideEffect||"read only"}</span><span>{s.approvalRequired?`Approval: ${s.approvalClass}`:"No approval"}</span></div><details><summary>Contract and recovery</summary><dl><div><dt>Required</dt><dd>{words(s.requiredParameters)}</dd></div><div><dt>Optional</dt><dd>{words(s.optionalParameters)}</dd></div><div><dt>Authentication</dt><dd>{words(s.authentication)}</dd></div><div><dt>Executor</dt><dd>{s.executor||"—"}</dd></div><div><dt>Verifier</dt><dd>{s.verifier||"—"}</dd></div><div><dt>Recovery</dt><dd>{s.recovery?.mode||"—"} · {s.recovery?.maxAutomaticRetries??0} retry</dd></div><div><dt>Accepts</dt><dd>{words(s.compatibleUpstreamOutputs)}</dd></div><div><dt>Produces for</dt><dd>{words(s.compatibleDownstreamInputs)}</dd></div></dl>{s.parameters&&<div className="parameter-ledger">{Object.entries(s.parameters).map(([name,v])=><span key={name}><b>{name}</b><small>{v.type} · {v.ownership}</small></span>)}</div>}</details><footer><button onClick={()=>p.onCommand("Use the "+s.name+" skill to: ")}>Use in Chat</button></footer></article>)}</div>{!rows.length&&<p className="empty-state">No matching skills.</p>}</Shell>
 }
 if(p.view==="system"){
  const patterns=o?.intelligence?.patterns||[],r=o?.reflex;
  return <Shell title="System" copy="Runtime health, deterministic intelligence, memory, and controls."><h2 className="section-title">Core runtime</h2><div className="metric-grid system-metrics">{(o?.services||[]).map(s=><article className="metric-card" key={s.id}><span>{s.label}</span><strong>{s.status}</strong><small>{s.detail}</small></article>)}</div><section className="system-columns"><article className="glass-panel reading-card"><h2>Local Reflex Engine</h2><p>{r?.mode||"In-process deterministic intelligence"}</p><div className="route-row"><div><b>{r?.contractCount||0} contracts</b><small>{r?.dimensions||0} dimensional hashed vectors</small></div><strong>{r?.estimatedVectorMemoryMb||0} MB</strong></div><div className="route-row"><div><b>No model process</b><small>{r?.cachedVectors||0} vectors cached</small></div><strong>{r?.externalProcess?"External":"Local"}</strong></div></article><article className="glass-panel reading-card"><h2>Models</h2><p>{p.models.filter(m=>m.configured&&!m.cooling).length} routes ready</p>{p.models.map(route=><div className="route-row" key={route.id}><div><b>{route.role}</b><small>{[route.provider,route.model,route.transport].filter(Boolean).join(" · ")||"Automatic"}</small></div><strong>{route.cooling?"Waiting":route.configured?"Ready":"Offline"}</strong></div>)}</article></section><section className="glass-panel intelligence-panel"><header><div><span className="eyebrow">INTELLIGENCE SNAPSHOT</span><h2>Scoped patterns</h2></div><span>{patterns.length} visible · {o?.memory.structuredCount||0} memories</span></header>{notice&&<p className="inline-alert" role="status">{notice}</p>}{patterns.map(row=><article className="pattern-row" key={row.id}><div><b>{row.description||row.subject}</b><small>{row.type} · {row.scope} · {row.evidenceCount} evidence · {pct(row.confidence)}</small></div><span className={"status-badge "+(row.status==="confirmed"?"success":"quiet")}>{row.status}</span><div><button disabled={!!working} onClick={()=>void pattern(row.id,"confirm")}>Confirm</button><button disabled={!!working} onClick={()=>void pattern(row.id,"disable")}>Disable</button><button disabled={!!working} onClick={()=>void pattern(row.id,"forget")}>Forget</button></div></article>)}{!patterns.length&&<p className="empty-state">No pattern has enough evidence to display yet.</p>}</section><details className="technical-disclosure glass-panel"><summary>Developer diagnostics</summary><dl><dt>Repository</dt><dd>{o?.workspace.repository||"Unavailable"}</dd><dt>Branch / commit</dt><dd>{o?.workspace.branch} · {o?.workspace.head}</dd><dt>Legacy skill instructions</dt><dd>{o?.legacySkillInstructions||0}</dd></dl><h3>Recent events</h3><pre>{JSON.stringify(p.events.slice(-20),null,2)}</pre></details></Shell>
 }
 const rows=manual.filter(x=>x.join(" ").toLowerCase().includes(query.toLowerCase()));
 return <Shell title="About ULTRON" copy="How Mark 4 selects work, learns safely, and recovers."><section className="glass-panel about-card"><div className="about-mark">U<span>4</span></div><div><span className="eyebrow">LOCAL OPERATING INTELLIGENCE</span><h2>Intent becomes verified execution.</h2><p>Deterministic first. Evidence visible. State recoverable.</p></div></section><input className="product-search" aria-label="Search product manual" placeholder="Search the manual…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="dictionary-grid">{rows.map(([title,copy])=><article key={title}><h2>{title}</h2><p>{copy}</p></article>)}</div>{!rows.length&&<p className="empty-state">No matching topic.</p>}</Shell>
}
function Shell(p:{title:string;copy:string;children:any}){return <section className="control-view page-flow"><header className="page-header"><div><span className="eyebrow">ULTRON MARK 4</span><h1>{p.title}</h1><p>{p.copy}</p></div></header>{p.children}</section>}
