import type{AttentionItem,IntegrationDescriptor,LiveEvent,Mission,ModelRoute,SystemOverview,ViewMode}from"../types";
const clean=(v:string)=>v.replace(/apollo-(?:contact-)?[0-9]+-[a-z0-9]+/g,"from the saved checkpoint");
const statusTone=(s:string)=>/complete|connected/i.test(s)?"success":/block|fail|invalid|unavailable/i.test(s)?"danger":/approval|auth|pause|degraded|rate/i.test(s)?"warning":"active";

export function HomeView(p:{missions:Mission[];events:LiveEvent[];models:ModelRoute[];overview:SystemOverview|null;attention:AttentionItem[];integrations:IntegrationDescriptor[];onNavigate:(v:ViewMode)=>void;onMission:(id:string)=>void;onCommand:()=>void}){
 const current=p.missions.find(m=>!["completed","failed","cancelled"].includes(m.status))||null,progress=current?.state?.progress as any,outputs=p.overview?.outputs||[],healthy=p.integrations.filter(x=>x.status==="CONNECTED").length,patterns=p.overview?.intelligence?.patterns||[],reflex=p.overview?.reflex;
 return <section className="home-view page-flow"><header className="home-focus glass-panel"><div><span className="eyebrow">CURRENT WORK</span><h1>{current?.objective||"ULTRON is ready."}</h1><p>{clean(current?.nextAction||"Start from Chat by text, voice, a file, or shared screen context.")}</p><div className="hero-actions"><button className="primary" onClick={current?()=>p.onMission(current.id):p.onCommand}>{current?"Open mission":"Ask ULTRON"}</button><button onClick={p.onCommand}>Open chat</button></div></div>{current&&<div className="mission-stage-orb"><strong>{progress?.total!=null?progress.completed+"/"+progress.total:current.status.toUpperCase()}</strong><span>{progress?.currentStage?.replaceAll("_"," ")||"Evidence driven"}</span></div>}</header>
 <section className="quick-command-row" aria-label="Quick commands"><button onClick={p.onCommand}><b>Discover leads</b><small>Compile a verified company workflow</small></button><button onClick={p.onCommand}><b>Enrich a Sheet</b><small>Resolve schema and contact parameters</small></button><button onClick={()=>p.onNavigate("mission")}><b>Resume work</b><small>Continue from a saved checkpoint</small></button><button onClick={()=>p.onNavigate("skills")}><b>Browse contracts</b><small>Inspect inputs, cost, and recovery</small></button></section>
 <div className="home-secondary"><section className="glass-panel attention-board"><header><div><span className="eyebrow">NEEDS ATTENTION</span><h2>{p.attention.length?p.attention.length+" actionable items":"Nothing needs intervention"}</h2></div></header>{p.attention.slice(0,6).map(a=><button key={a.id} onClick={()=>a.missionId?p.onMission(a.missionId):p.onNavigate("integrations")}><i className={statusTone(a.type)}/><span><b>{a.type.replaceAll("_"," ")} · {a.title}</b><small>{clean(a.detail)}</small></span></button>)}{!p.attention.length&&<p className="verified-line">Active work can continue safely.</p>}</section><section className="glass-panel output-peek"><header><div><span className="eyebrow">RECENT OUTPUT</span><h2>{outputs.length?"Latest verified result":"No output yet"}</h2></div><button onClick={()=>p.onNavigate("outputs")}>View all</button></header>{outputs.slice(0,3).map((o:any,i)=><div key={i}><b>{String(o.name||o.type||"Output")}</b><small>{String(o.verification||o.destination||"Recorded")}</small></div>)}</section></div>
 <section className="glass-panel intelligence-home"><header><div><span className="eyebrow">INTELLIGENCE SNAPSHOT</span><h2>{patterns.length?patterns.length+" scoped patterns":"Learning remains evidence gated"}</h2></div><button onClick={()=>p.onNavigate("system")}>Review controls</button></header><div><span><b>{reflex?.contractCount||0}</b><small>skill contracts</small></span><span><b>{reflex?.estimatedVectorMemoryMb||0} MB</b><small>reflex vectors</small></span><span><b>{p.overview?.memory.structuredCount||0}</b><small>structured memories</small></span><span><b>{reflex?.externalProcess?"External":"In process"}</b><small>execution mode</small></span></div></section>
 <div className="home-health"><button className="quiet-stat" onClick={()=>p.onNavigate("integrations")}><span>ACTIVE SYSTEMS</span><b>{healthy} integrations connected</b><small>{p.integrations.length-healthy} need setup or attention</small></button><button className="quiet-stat" onClick={()=>p.onNavigate("system")}><span>SYSTEM HEALTH</span><b>{p.models.filter(m=>m.configured&&!m.cooling).length} model routes ready</b><small>{p.overview?.services?.every(s=>!["unavailable","degraded"].includes(s.status))?"Operational":"Needs attention"}</small></button></div></section>;
}
