import { useEffect, useMemo, useRef, useState } from "react";
import { activityFrom, type ActivityCategory } from "../activity";
import type { LiveEvent, ModelRoute } from "../types";
const filters:Array<"ALL"|ActivityCategory>=["ALL","REQUEST","MODEL","SKILL","TOOL","SEARCH","MEMORY","WRITE","APPROVAL","MISSION","RESULT","WARNING","ERROR","VOICE"];
export function LiveActivity({events,route,onClose}:{events:LiveEvent[];route?:ModelRoute|null;onClose?:()=>void}){
 const[paused,setPaused]=useState(false),[filter,setFilter]=useState<"ALL"|ActivityCategory>("ALL"),[clearedAt,setClearedAt]=useState(0);const end=useRef<HTMLDivElement|null>(null);
 const items=useMemo(()=>events.map(event=>activityFrom(event,route)).filter(Boolean).filter(item=>new Date(item!.event.at).getTime()>=clearedAt).filter(item=>filter==="ALL"||item!.category===filter),[events,route,clearedAt,filter]);
 useEffect(()=>{if(!paused)end.current?.scrollIntoView({block:"end",behavior:"smooth"})},[items.length,paused]);
 return <aside className="live-activity"><header><div><span className="panel-eyebrow"><i/>LIVE</span><h2>Activity</h2></div>{onClose&&<button onClick={onClose} aria-label="Close activity">×</button>}</header><div className="activity-controls"><select value={filter} onChange={e=>setFilter(e.target.value as any)} aria-label="Filter activity">{filters.map(value=><option key={value}>{value}</option>)}</select><button className={paused?"active":""} onClick={()=>setPaused(v=>!v)}>{paused?"Resume":"Pause"}</button><button onClick={()=>setClearedAt(Date.now())}>Clear</button></div><div className="activity-stream">{items.length?items.map((item,index)=><details className={"activity-entry tone-"+item!.tone} key={item!.event.at+"-"+index}><summary><time>{new Date(item!.event.at).toLocaleTimeString([],{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit"})}</time><i/><div><span>{item!.category}</span><b>{item!.title}</b>{item!.detail&&<small>{item!.detail}</small>}</div></summary><pre>{JSON.stringify(item!.event.data,null,2)}</pre></details>):<div className="activity-empty"><span>◌</span><b>No matching activity</b><small>Observed gateway events will appear here.</small></div>}<div ref={end}/></div><footer><span>{items.length} observed</span><span>{paused?"AUTO-SCROLL PAUSED":"FOLLOWING LIVE"}</span></footer></aside>
}
