import {useState} from "react";
import type {Mission} from "../types";
import {Icon} from "./Icon";

export const missionState=(m:Mission)=>{const s=m.status,a=String(m.state?.attentionState||"");if(s==="completed")return{label:"Completed",tone:"success",symbol:"✓",lane:"RECENT"};if(s==="failed"||s==="cancelled")return{label:s==="failed"?"Failed":"Cancelled",tone:"danger",symbol:"×",lane:"RECENT"};if(s==="paused")return{label:"Paused",tone:"warning",symbol:"Ⅱ",lane:"WAITING"};if(s==="awaiting_approval"||a==="APPROVAL_REQUIRED")return{label:"Waiting approval",tone:"warning",symbol:"!",lane:"WAITING"};if(a==="MISSING_PARAMETER"||s==="waiting_input")return{label:"Waiting input",tone:"warning",symbol:"?",lane:"WAITING"};if(/blocked|waiting/.test(s))return{label:s==="blocked"?"Blocked":"Waiting",tone:"warning",symbol:"!",lane:"WAITING"};return{label:s==="verifying"?"Verifying":"Running",tone:"active",symbol:s==="verifying"?"✓":"↻",lane:"ACTIVE"};};
const L=(v:string)=>String(v||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const T=(v?:string)=>v?new Date(v).toLocaleString([],{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}):"";
const progressOf=(m:Mission)=>(m.state as any)?.progress||m.progress;
const tabs=["overview","progress","parameters","evidence","outputs","activity","branches"];

export function MissionView(p:{missions:Mission[];activeId:string;detail?:Mission|null;onSelect:(id:string)=>void;onNew:()=>void;onOpenSession:(id:string)=>void;onUpdate:(id:string,patch:Record<string,unknown>)=>Promise<void>}){
 const[busy,setBusy]=useState(""),[error,setError]=useState(""),[tab,setTab]=useState("overview");
 const selected=p.activeId?(p.detail?.id===p.activeId?p.detail:p.missions.find(x=>x.id===p.activeId)):null;
 async function action(m:Mission,status:string){if(busy)return;setBusy(m.id);setError("");try{await p.onUpdate(m.id,{status,...(status==="cancelled"?{nextAction:null}:{})})}catch(e:any){setError(e.message||"Could not update mission. Please retry.")}finally{setBusy("")}}
 const actions=(m:Mission)=>{const state=missionState(m);return <div className="mission-actions">{state.lane!=="RECENT"&&<button disabled={!!busy} onClick={()=>void action(m,m.status==="paused"||m.status==="blocked"?"active":"paused")}>{busy===m.id?"Updating…":m.status==="paused"||m.status==="blocked"?"Resume":"Pause"}</button>}</div>};
 if(!selected)return <section className="mission-board page-flow"><header className="page-header"><div><span className="eyebrow">YOUR WORK</span><h1>Missions</h1><p>Follow active work, resolve decisions, and revisit verified results.</p></div><button className="primary-action" onClick={p.onNew}><Icon name="plus"/>New mission</button></header>{error&&<p role="alert" className="inline-alert">{error}</p>}{["ACTIVE","WAITING","RECENT"].map(lane=>{const rows=p.missions.filter(m=>missionState(m).lane===lane).slice(0,lane==="RECENT"?12:100);return <section className="mission-lane" key={lane}><header><h2>{lane}</h2><span>{rows.length}</span></header><div>{rows.map(m=>{const s=missionState(m),pr=progressOf(m),metrics=(m.state as any)?.metrics||{};return <article className={"mission-board-card glass-panel state-"+s.tone} key={m.id}><header><span className={"status-badge "+s.tone}>{s.symbol} {s.label}</span><time>{T(m.updatedAt)}</time></header><h3>{m.objective}</h3><small className="mission-source">{(m.state as any)?.skillInvocation?.skillId||(/apollo/i.test(JSON.stringify(m.state))?"Apollo · Google Sheets":"ULTRON mission")}</small><div className="card-progress"><b>{pr?.total!=null?pr.completed+" / "+pr.total:"—"}</b><span>{pr?.currentItem||L(pr?.currentStage||"Progress pending")}</span></div><div className="card-counts">{metrics.fullMatch!=null&&<span>{metrics.fullMatch} enriched</span>}{metrics.partialMatch!=null&&<span>{metrics.partialMatch} partial</span>}{metrics.noMatch!=null&&<span>{metrics.noMatch} no match</span>}</div><footer><button className="primary" onClick={()=>{setTab("overview");p.onSelect(m.id)}}>Open</button>{actions(m)}</footer></article>})}{!rows.length&&<div className="lane-empty"><span>{lane==="ACTIVE"?"No active missions.":lane==="WAITING"?"No decisions waiting.":"Completed work will appear here."}</span>{lane==="ACTIVE"&&<button onClick={p.onNew}>Ask ULTRON</button>}</div>}</div></section>})}</section>;
 const m=selected,pr=progressOf(m),tasks=pr?.stages||[],metrics=(m.state as any)?.metrics||{},s=missionState(m),invocation=(m.state as any)?.skillInvocation||{};
 const outputList=m.outputs||[];
 return <section className="mission-detail-page page-flow"><button className="back-link" onClick={()=>p.onSelect("")}>← All missions</button><header className="detail-hero"><div><span className={"status-badge "+s.tone}>{s.symbol} {s.label}</span><h1>{m.objective}</h1>{m.objective.length>120&&<details className="objective-disclosure"><summary>Full objective</summary><p>{m.objective}</p></details>}<p>{m.nextAction||"Follow progress and review the result below."}</p></div><div className="mission-actions">{actions(m)}{s.lane!=="RECENT"&&<button disabled={!!busy} className="danger" onClick={()=>void action(m,"cancelled")}>Stop</button>}{m.sessionId&&<button onClick={()=>p.onOpenSession(m.sessionId!)}>Open chat</button>}</div></header>{error&&<p role="alert" className="inline-alert">{error}</p>}<nav className="mission-detail-tabs" aria-label="Mission details">{tabs.map(x=><button key={x} className={tab===x?"active":""} aria-current={tab===x?"page":undefined} onClick={()=>setTab(x)}>{L(x)}</button>)}</nav>
 {tab==="overview"&&<><section className="mission-progress glass-panel"><header><div><span className="eyebrow">LIVE PROGRESS</span><h2>{L(pr?.currentStage||"Waiting for progress")}</h2></div><strong>{pr?.total!=null?pr.completed+" / "+pr.total:"Pending"}</strong></header>{pr?.currentItem&&<p>Current item · <b>{pr.currentItem}</b></p>}<ol className="stage-track" aria-label="Mission stages">{tasks.map((stage:any,i:number)=><li className={"stage-node "+stage.status} aria-current={stage.status==="active"?"step":undefined} key={stage.id||i}><i aria-hidden="true">{stage.status==="completed"?"✓":stage.status==="blocked"?"!":i+1}</i><span><b>{stage.label}</b><small>{L(stage.status)}{stage.summary?" · "+stage.summary:""}</small></span></li>)}</ol></section><section className="mission-metrics">{[["Processed",metrics.processed],["Full match",metrics.fullMatch],["Partial",metrics.partialMatch],["No match",metrics.noMatch],["Requests",metrics.requests],["Remaining",metrics.remaining]].map(([k,v])=><div key={String(k)}><span>{k}</span><b>{v??"—"}</b></div>)}</section><div className="mission-grid"><section className="detail-section"><h2>Attention</h2>{m.blockers?.map((x:any,i)=><p className="attention-item" key={i}><Icon name="warning"/>{String(x.message||x.code||x)}</p>)}{!m.blockers?.length&&<p className="verified-line"><Icon name="check"/>No blockers</p>}</section><section className="detail-section"><h2>Selection</h2><p>{invocation.skillId||"Direct mission"}</p><small>{invocation.selection?.source||"Mission runtime"} · {invocation.selection?.confidence?Math.round(invocation.selection.confidence*100)+"% confidence":"confidence unavailable"}</small></section></div></>}
 {tab==="progress"&&<section className="detail-section"><h2>Stage checkpoints</h2><ol className="stage-track">{tasks.map((stage:any,i:number)=><li className={"stage-node "+stage.status} key={stage.id||i}><i>{stage.status==="completed"?"✓":i+1}</i><span><b>{stage.label}</b><small>{stage.summary||L(stage.status)}</small></span></li>)}</ol>{!tasks.length&&<p>No stage checkpoint has been recorded.</p>}</section>}
 {tab==="parameters"&&<section className="detail-section"><h2>Compiled parameters</h2>{Object.entries(invocation.parameters||{}).map(([key,value])=><div className="route-row" key={key}><div><b>{L(key)}</b><small>{invocation.parameterEvidence?.[key]?.source||"unknown source"}</small></div><strong>{typeof value==="object"?JSON.stringify(value):String(value)}</strong></div>)}{!Object.keys(invocation.parameters||{}).length&&<p>No structured invocation is attached.</p>}</section>}
 {tab==="evidence"&&<section className="detail-section"><h2>Evidence</h2>{(m.evidence||[]).map((e,i)=><article className="pattern-row" key={e.id||i}><div><b>{L(e.kind)}</b><small>{e.source} · {e.verified?"verified":"unverified"}</small></div>{e.ref&&<code>{e.ref}</code>}</article>)}{!m.evidence?.length&&<p>No evidence has been recorded.</p>}</section>}
 {tab==="outputs"&&<section className="detail-section"><h2>Outputs</h2>{outputList.map((o:any,i)=><div key={i}>{o.url&&/^https?:\/\//i.test(o.url)?<a className="mission-output" href={o.url} target="_blank" rel="noreferrer">{o.name||L(o.type)} <Icon name="arrow"/></a>:<p>{o.name||L(o.type)||"Result recorded"}</p>}</div>)}{!outputList.length&&<p>Verified results will appear here.</p>}</section>}
 {tab==="activity"&&<section className="detail-section"><h2>Activity</h2><div className="timeline">{m.events?.slice().reverse().map((e,i)=><div key={e.id||i}><time>{T(e.createdAt)}</time><b>{L(e.type)}</b></div>)}</div>{!m.events?.length&&<p>No activity events recorded.</p>}</section>}
 {tab==="branches"&&<section className="detail-section"><h2>Conversation branches</h2>{m.relatedSessions?.map(id=><button className="mission-output" key={id} onClick={()=>p.onOpenSession(id)}>Open session {id.slice(0,8)}</button>)}{m.childBranches?.map(id=><button className="mission-output" key={id} onClick={()=>p.onOpenSession(id)}>Open branch {id.slice(0,8)}</button>)}{!m.relatedSessions?.length&&!m.childBranches?.length&&<p>No conversation branch is linked.</p>}</section>}
 </section>;
}
