import {useState} from "react";
import type {Mission,SystemOverview} from "../types";
import {Icon} from "./Icon";
export function safeOutputUrl(value:unknown){try{if(!value||! /^(https?:\/\/|\/api\/)/i.test(String(value)))return null;const u=new URL(String(value),location.origin);return ["http:","https:"].includes(u.protocol)?u.href:null}catch{return null}}
function Preview({url,video}:{url:string;video:boolean}){const[failed,setFailed]=useState(false);return failed?<p className="preview-fallback">Preview unavailable. Use the result link below.</p>:video?<video controls preload="none" src={url} onError={()=>setFailed(true)} aria-label="Video preview"/>:<img loading="lazy" src={url} alt="Deliverable preview" onError={()=>setFailed(true)}/>}
export function OutputsView({overview,missions}:{overview:SystemOverview|null;missions:Mission[]}){
 const[filter,setFilter]=useState("All"),outputs=(overview?.outputs||[]).filter((o:any)=>!o.diagnostic&&!o.fixture&&!/\b(selftest|fixture|mock|test output)\b/i.test(String(o.name||"")));
 const typeOf=(o:any)=>/sheet/i.test(o.type)?"Sheets":/reel|video/i.test(o.type)?"Reels":/lead/i.test(o.type)?"Leads":/code|commit|diff/i.test(o.type)?"Code":"Documents";
 const rows=outputs.filter(o=>filter==="All"||typeOf(o)===filter);
 return <section className="control-view page-flow"><header className="page-header"><div><span className="eyebrow">YOUR RESULTS</span><h1>Outputs</h1><p>Review deliverables, check verification, and open the result.</p></div></header><div className="filter-bar" role="group" aria-label="Filter outputs">{["All","Sheets","Reels","Leads","Documents","Code"].map(f=><button aria-pressed={filter===f} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="output-grid">{rows.map((o:any,i)=>{const type=typeOf(o),href=safeOutputUrl(o.openAction?.url||o.url||""),preview=o.preview?safeOutputUrl(o.preview):null,m=missions.find(m=>m.id===o.missionId),verification=String(o.verification||"Not verified"),verified=!/not|unverified|pending|failed/i.test(verification)&&/verified/i.test(verification);return <article className="output-card glass-panel" key={String(o.missionId||"result")+i}><header><span><Icon name={type==="Code"?"branches":type==="Sheets"?"operations":type==="Reels"?"command":"attach"}/>{type}</span><b className={"status-badge "+(verified?"success":"quiet")}>{verified?"✓ Verified":"Review"}</b></header>{preview&&<Preview key={preview} url={preview} video={/\.(mp4|webm)(\?|$)/i.test(preview)}/>}<h2>{String(o.worksheet||o.name||m?.objective||type+" result")}</h2><p className="output-origin">{String(o.sourceIntegration||"ULTRON")}{o.timestamp?" · "+new Date(o.timestamp).toLocaleDateString():""}</p><dl>{Object.entries({Verification:verification,...(type==="Sheets"?{Rows:o.verifiedRows??o.rowsUpdated??"Not reported",Range:o.range||o.destination||"Not reported"}:type==="Reels"?{Duration:o.duration||"Not reported",Resolution:o.resolution||"Not reported"}:type==="Leads"?{Companies:o.companyCount??o.count??"Not reported",Enriched:o.enrichedCount??"Not reported"}:type==="Code"?{Branch:o.branch||"Not reported",Commit:o.commit||"Not reported",Tests:o.tests||"Not reported"}:{Destination:o.destination||"Local result"})}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl>{href&&Boolean(o.openAction?.url||o.url)?<a className="button-link" href={href} target="_blank" rel="noreferrer">{type==="Code"?"Open diff":"Open"} <Icon name="arrow"/></a>:<p className="preview-fallback">No link available. Open the related mission for details.</p>}</article>})}</div>{!rows.length&&<div className="empty-state glass-panel"><Icon name="attach"/><b>Verified results will appear here.</b><span>{filter==="All"?"Start a mission in Chat to create your first deliverable.":"No results match this filter."}</span></div>}</section>
}
