import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import path from"node:path";import{fileURLToPath}from"node:url";import{compileCommand}from"../src/command-control-plane.mjs";import{attentionFor,normalizeOutput,visibleMissions,STRUCTURED_STATES}from"../src/attention.mjs";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../..");const read=p=>fs.readFileSync(path.join(root,p),"utf8");
test("screen context supplies the open Google Sheet without DOM scraping",()=>{const intent=compileCommand("Enrich the Sheet I have open",{page:{url:"https://docs.google.com/spreadsheets/d/abc-123/edit?gid=77"}});assert.equal(intent.domain,"apollo-contact-enrichment");assert.equal(intent.sheet.spreadsheetId,"abc-123");assert.equal(intent.sheet.sheetId,77);assert.equal(intent.sheet.source,"screen-context")});
test("phone requirement is explicit while Indian numbers remain a preference",()=>{assert.equal(compileCommand("Enrich this Sheet with Apollo").requirements.indianPhoneRequired,false);assert.equal(compileCommand("Enrich this Sheet with Apollo; contacts must have Indian phone numbers").requirements.indianPhoneRequired,true)});
test("canonical attention includes structured mission and integration states",()=>{const items=attentionFor([{id:"m",objective:"Enrich",status:"blocked",state:{attentionState:"MISSING_PARAMETER",pendingParameter:{prompt:"Which worksheet?",options:[{title:"Leads"}]}},blockers:[]}],[{id:"google",name:"Google",status:"AUTH_REQUIRED",detail:"Connect"}]);assert.deepEqual(items.map(x=>x.type),["MISSING_PARAMETER","AUTH_REQUIRED"]);assert.equal(items[0].choices[0].title,"Leads")});
test("diagnostic missions are hidden from normal product surfaces",()=>{assert.deepEqual(visibleMissions([{objective:"gateway self-test"},{objective:"Customer lead run"}]).map(x=>x.objective),["Customer lead run"])});
test("outputs expose normalized verification and open action",()=>{const out=normalizeOutput({type:"google_sheet",name:"Leads",url:"https://docs.google.com/x",verifiedRows:3},{id:"m",objective:"Lead run",updatedAt:"2026-01-01T00:00:00Z"});assert.equal(out.verification,"3 rows verified");assert.equal(out.sourceIntegration,"Google Workspace");assert.equal(out.openAction.label,"Open output")});
test("UI exposes secure integrations, screen permission, mission lanes and no Workspace nav",()=>{const app=read("apps/ui/src/App.tsx"),chat=read("apps/ui/src/components/CommandView.tsx"),integrations=read("apps/ui/src/components/IntegrationsView.tsx"),missions=read("apps/ui/src/components/MissionView.tsx");assert.match(app,/label:"Integrations"/);assert.doesNotMatch(app,/label:"Workspace"/);assert.match(chat,/getDisplayMedia/);assert.match(chat,/Stop sharing/);assert.match(chat,/pendingParameter/);assert.match(integrations,/Windows DPAPI/);for(const lane of["ACTIVE","WAITING","RECENT"])assert.match(missions,new RegExp(lane))});
test("gateway owns nonfatal states and secure integration actions",()=>{const server=read("services/gateway/src/server.mjs"),runner=read("services/gateway/src/apollo-contact-mission.mjs"),store=read("services/capability-host/src/secure-credentials.mjs");for(const state of["MISSING_PARAMETER","SCREEN_PERMISSION_REQUIRED","AUTH_REQUIRED","RATE_LIMITED","BLOCKED"])assert.match(server+runner,new RegExp(state));for(const state of["FULL_MATCH","PARTIAL_MATCH","NO_MATCH"])assert.match(runner,new RegExp(state));assert.match(store,/ProtectedData/);assert.match(server,/api\/integrations/)});

test("all expected operational states are structured",()=>assert.deepEqual(STRUCTURED_STATES,["APPROVAL_REQUIRED","AUTH_REQUIRED","MISSING_PARAMETER","SCREEN_PERMISSION_REQUIRED","INTEGRATION_REQUIRED","RATE_LIMITED","NO_MATCH","PARTIAL_RESULT","BLOCKED"]));
