import type { LiveEvent, Mission, ModelRoute } from "./types";
export type CoreState="idle"|"listening"|"transcribing"|"understanding"|"model"|"skill"|"tool"|"mission"|"approval"|"writing"|"speaking"|"completed"|"fallback"|"offline"|"error";
export type ActivityCategory="REQUEST"|"ROUTING"|"MODEL"|"SKILL"|"TOOL"|"SEARCH"|"MEMORY"|"WRITE"|"APPROVAL"|"MISSION"|"RESULT"|"WARNING"|"ERROR"|"VOICE"|"SYSTEM";
export interface ActivityItem{event:LiveEvent;category:ActivityCategory;title:string;detail:string;state:CoreState;tone:"neutral"|"active"|"success"|"warning"|"danger"}
const words=(v:unknown)=>String(v??"").replace(/^ultron[_/.:-]?/i,"").replace(/[_.:/-]+/g," ").replace(/\s+/g," ").trim();
const pick=(d:any,...keys:string[])=>keys.map(k=>d?.[k]).find(v=>v!==undefined&&v!==null&&String(v).trim())??"";
export const titleCase=(v:unknown)=>words(v).replace(/\b\w/g,x=>x.toUpperCase());
export const modelLabel=(d:any,r?:ModelRoute|null)=>[pick(d,"provider")||r?.provider,pick(d,"model")||r?.model].filter(Boolean).map(titleCase).join(" · ")||titleCase(pick(d,"route")||"Hermes Auto");
const tool=(d:any)=>words(pick(d,"display_name","tool_name","tool","name","capability")||"runtime tool");
export function capabilityFor(e?:LiveEvent|null){const raw=(e?.type+" "+JSON.stringify(e?.data||{})).toLowerCase();if(/apollo|lead|contact|enrich/.test(raw))return"Apollo Lead Intelligence";if(/google|sheet|drive|workspace/.test(raw))return"Google Workspace Operations";if(/linkedin/.test(raw))return"LinkedIn Company Research";if(/creator|instagram|influencer/.test(raw))return"Elevate Creator Research";if(/github|code|terminal|filesystem|patch|build/.test(raw))return"Coding & Publishing";if(/reel|ffmpeg|video|media|image/.test(raw))return"Media Production";if(/memory|context/.test(raw))return"Memory & Context";if(/web|browser|search|research/.test(raw))return"Adaptive Research";return e?.type.startsWith("skill.")?titleCase(pick(e.data,"skill","name","display_name")):"Hermes Cognition"}
const prog=(d:any)=>{const c=Number(pick(d,"current","completed","qualified","written","count")),t=Number(pick(d,"target","total","requested"));return Number.isFinite(c)&&Number.isFinite(t)&&t>0?`${c} / ${t}`:""};
export function activityFrom(event:LiveEvent,route?:ModelRoute|null):ActivityItem|null{const d:any=event.data||{},t=event.type.replace(/_/g,"."),s=String(pick(d,"summary","message","status","phase","description")||"");if(t==="assistant.delta"||t==="message.started"||t==="done")return null;
let category:ActivityCategory="SYSTEM",title=titleCase(t),detail=s,state:CoreState="idle",tone:ActivityItem["tone"]="neutral";
if(t==="connected"||t==="connection.online")return{event,category,title:"ULTRON online",detail:"Gateway event stream connected",state,tone:"success"};
if(t==="connection.offline")return{event,category:"ERROR",title:"Gateway connection lost",detail:s||"Retrying with bounded backoff",state:"offline",tone:"danger"};
if(t==="request.received"){category="REQUEST";title="Command received";detail=s||"Accepted by the Mark 4 gateway";state="understanding";tone="active"}
else if(t==="model.selected"){category="MODEL";title=modelLabel(d,route);detail="Selected for this run";state="model";tone="active"}
else if(t==="model.route.failed"){category="WARNING";title=titleCase(pick(d,"provider","route")||"Provider fallback");detail=titleCase(pick(d,"errorClass")||s);state="fallback";tone="warning"}
else if(t==="skill.selected"){category="SKILL";title=titleCase(pick(d,"skill","name")||capabilityFor(event));detail=s||"Capability activated from an observed tool call";state="skill";tone="active"}
else if(t.startsWith("tool.")){const name=tool(d),failed=t.endsWith("failed"),done=t.endsWith("completed");category=/search|apollo|linkedin|browser/.test(name)?"SEARCH":/sheet|write|upsert|save/.test(name)?"WRITE":done?"RESULT":"TOOL";title=titleCase(name);detail=prog(d)||s||(done?"Operation completed":failed?String(pick(d,"error")||"Operation failed"):"Execution started");state=failed?"error":done?"completed":category==="WRITE"?"writing":"tool";tone=failed?"danger":done?"success":"active"}
else if(t.startsWith("memory.")){category="MEMORY";title="Context loaded";detail=prog(d)||s||titleCase(pick(d,"source")||"Relevant memory recovered");state="understanding"}
else if(t==="approval.request"||t==="approval.required"){category="APPROVAL";title="Approval required";detail=titleCase(pick(d,"tool_name","tool","kind")||s||"External action");state="approval";tone="warning"}
else if(t==="approval.granted"){category="APPROVAL";title="Approval granted";detail=titleCase(pick(d,"choice")||"Once");state="tool";tone="success"}
else if(t.startsWith("mission.")){const done=t.endsWith("completed");category=done?"RESULT":"MISSION";title=done?"Mission completed":titleCase(pick(d,"phase","status")||t);detail=prog(d)||s||String(pick(d,"objective","nextAction")||"");state=done?"completed":"mission";tone=done?"success":"active"}
else if(t==="run.started"){category="ROUTING";title="Runtime engaged";detail=titleCase(pick(d,"role","route")||"Cognition run");state="understanding";tone="active"}
else if(t==="run.settled"||t==="run.completed"){category="RESULT";title="Response completed";detail=d.latencyMs?`${(Number(d.latencyMs)/1000).toFixed(1)}s runtime`:s;state="completed";tone="success"}
else if(t==="run.failed"||t==="error"){category="ERROR";title="Execution failed";detail=String(pick(d,"error","message")||"Runtime error");state="error";tone="danger"}
else if(t==="artifact.created"){category="RESULT";title="Artifact created";detail=String(pick(d,"name","path","url")||s);state="completed";tone="success"}
else if(t.startsWith("voice.")){category="VOICE";const v=t.slice(6);title=titleCase(v);detail=s||"Live voice mode";state=(v==="transcribed"?"transcribing":v) as CoreState;tone=v==="error"?"danger":"active"}
return{event,category,title,detail,state,tone}}
export function operationalState(events:LiveEvent[],o:{online:boolean;voiceState?:CoreState;busy?:boolean;approval?:boolean}){if(!o.online)return activityFrom({type:"connection.offline",data:{},at:new Date().toISOString()})!;if(o.voiceState&&o.voiceState!=="idle")return{event:{type:"voice."+o.voiceState,data:{},at:""},category:"VOICE" as ActivityCategory,title:titleCase(o.voiceState),detail:"Live voice mode",state:o.voiceState,tone:"active" as const};if(o.approval)return activityFrom({type:"approval.request",data:{},at:""})!;for(let i=events.length-1;i>=0;i--){const item=activityFrom(events[i]);if(item&&item.state!=="idle")return item}return{event:{type:"idle",data:{},at:""},category:"SYSTEM" as ActivityCategory,title:o.busy?"Understanding request":"Cognition ready",detail:o.busy?"Waiting for the next observed operation":"Give ULTRON a command",state:o.busy?"understanding" as CoreState:"idle" as CoreState,tone:"neutral" as const}}
export function missionProgress(m?:Mission|null){const s:any=m?.state||{},c:any=m?.completionCriteria||{};const current=Number(s.current??s.completed??s.qualified??s.written),target=Number(s.target??c.target);return{current:Number.isFinite(current)?current:null,target:Number.isFinite(target)&&target>0?target:null}}
